---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:          ## 메인 컨테이너
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: contents-vol
      readOnly: true
      
  - name: cloner       ## 사이드카 컨테이너
    image: teri0411/contents-cloner:1.0
    env:
    - name: CONTENTS_SOURCE_URL
      value: "https://github.com/teri0411/k8s_sidecarTest"
    volumeMounts:
    - mountPath: /data
      name: contents-vol
      
  volumes:             ## 공유 볼륨
  - name: contents-vol
    emptyDir: {}